#!/bin/bash

curl --location --request POST 'localhost:9001/uk/api/v3/submit-survey' \
    --header 'Content-Type: application/json' \
    --header 'access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c24iOiJrYWJhdGJwIiwicm9sIjoiRk8iLCJleHAiOjE2NjMxMDEyNjYsImp0aSI6IjE0NjEiLCJpYXQiOjE2NjMwNDEyNjYsImlzcyI6ImdvLWNhcyIsIm5iZiI6MTY2MzA0MTI2Niwic3ViIjoiQVBQIn0.KIQcS2NezWP7htiiSWmnUPbFtWvOiz4nCQSifjdem-8' \
    --header 'assignee: AGENT' \
    --header 'assigneeId: 1461' \
    --header 'Accept: application/vnd.amartha.superapp+json;version=3' \
    --data-raw '{
  "actualLocation": {
    "latitude": -0.1942736,
    "longitude": 100.5796257
  },
  "agentId": 1461,
  "borrowerConsent": true,
  "branchId": 380,
  "fullname": "Test Double Submit",
  "groupId": 1000008734,
  "isLoadNik": false,
  "isOcr": false,
  "raw": {
    "client_fullname_id_card": "Test Double Submit",
    "client_ktp": "3573210912984103",
    "photo_kk": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/8116c19e-e24c-4874-a12f-2b033c780d02.jfif",
    "client_job_geotagging": {
      "latitude": -0.19424252256835878,
      "longitude": 100.57965226471424,
      "name": "Custom Address"
    },
    "photo_ktp": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/36cda798-ea65-456b-917d-4e4af524c7cd.jfif",
    "photo_penanggung_jawab": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/18f775dd-f030-467e-ba64-8a06b0f0a220.jfif",
    "geotagging": {
      "latitude": -0.19424252256835878,
      "longitude": 100.57965226471424,
      "name": "Custom Address"
    },
    "photo_client": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/f02d1e47-1d05-42ce-8ce2-558cd2a01da4.jfif",
    "photo_client_square": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/e83f39d7-d9ea-4518-a9d2-e1d23186e93f.jfif",
    "photo_client_selfie": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/4234ee38-fd3c-4e66-8389-8fd45fe2be94.jfif",
    "geotagging_penanggung_jawab": {
      "latitude": -0.19424252256835878,
      "longitude": 100.57965226471424,
      "name": "Custom Address"
    },
    "photo_ktp_penanggung_jawab": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/16d2f6d4-2441-4407-8ee9-18b970bf4581.jfif",
    "photo_client_house": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/f299515d-f988-4820-988b-37b0c7fc50ad.jfif",
    "loanType": "NORMAL",
    "client_fullname": "Test Phone Number Validation C",
    "client_alias": "Sarimin Satu",
    "client_branch": 380,
    "client_total_income_keluarga_monthly": 12000000,
    "client_expense_per_month": 0,
    "client_job_expense_monthly": 0,
    "client_job_phone_no": "085213469578",
    "client_job_type": "Wirausaha",
    "client_job_name": "Usaha Ibu satu",
    "client_job_negara": "Indonesia",
    "client_jenis_kelamin": "Perempuan",
    "client_other_loan_total": -1,
    "client_other_loan_total_amount": -1,
    "data_pendapatan_istri_monthly": 12000000,
    "data_akad": "MBA",
    "data_tgl": "2022-02-08",
    "job_type_penanggung_jawab": "Wirausaha",
    "other_loan_instance_name": "",
    "other_loan_weekly_installment_monthly": 0,
    "client_job_rt": "002",
    "client_job_rw": "003",
    "client_job_kode_pos": "12760",
    "client_job_provinsi": "DKI Jakarta",
    "client_job_kota_kab": "Jakarta Selatan",
    "client_job_kecamatan": "Pancoran",
    "client_job_desa": "Duren Tiga",
    "data_suami": "gertu",
    "client_alias_penanggung_jawab": "gertu",
    "tanggungan": "[]",
    "uuid": "86e5c71d-533b-4e95-ac25-86ad752be586",
    "client_kota_kab": "Jakarta Selatan",
    "client_kota_kab_id": 56,
    "client_sumber_dana": "hasil_usaha",
    "client_provinsi": "DKI Jakarta",
    "client_provinsi_id": 31,
    "client_total_income_keluarga": "3000000",
    "client_nationality": "wni",
    "client_alamat": "jakarta",
    "client_birthplace": "medan",
    "client_desa": "Duren Tiga",
    "client_desa_id": 4730,
    "client_domicile_equals_id_card": "sama_dengan_id_card",
    "client_phone": "081313070541",
    "client_kecamatan": "Pancoran",
    "client_kecamatan_id": 727,
    "client_identity_type": "ktp",
    "client_id_card_valid_type": "seumur_hidup",
    "data_client_kehamilan": "Tidak Hamil dan Tidak Menyusui",
    "client_religion": "Islam",
    "client_permanent_resident": true,
    "client_kode_pos": "12760",
    "client_alamat_rekening_koran": "id_card_address",
    "client_other_loan": [],
    "client_birthdate": "1952-02-08",
    "client_education": "Perguruan Tinggi & Sederajat",
    "client_rt": "002",
    "client_rw": "003",
    "client_ibu_kandung": "santini",
    "client_expense_per_week": "0",
    "client_maritalstatus": "Belum Menikah",
    "client_job_expense": "0",
    "data_pendapatan_istri": "3000000",
    "client_domicile_alamat": "jakarta",
    "client_domicile_rt": "002",
    "client_domicile_rw": "003",
    "client_domicile_kode_pos": "12760",
    "client_domicile_provinsi": "DKI Jakarta",
    "client_domicile_kota_kab": "Jakarta Selatan",
    "client_domicile_kecamatan": "Pancoran",
    "client_domicile_desa": "Duren Tiga",
    "client_job_address": "jakarta",
    "data_client_umur": 40,
    "is_tnc_approved":false,
    "client_id_card_valid_through": "2072-02-08",
    "kecamatan_penanggung_jawab_id": 727,
    "client_face_identity": {
      "is_enrolled": true
    },
    "client_digital_signature": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/674be1b2-2cda-43ca-b6b6-ec0c9b5541e9.jfif",
    "client_pj_digital_signature":"",
    "client_job": "C32909",
    "data_pendapatan_lain": "3000000",
    
      "rekening_mitra_nama":        "Yuhu",
      "rekening_mitra_bank_tujuan": "BRI",
      "rekening_mitra_no_rekening": "123456789012345",
    
          "photo_buku_tabungan":"https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/4234ee38-fd3c-4e66-8389-8fd45fe2be94.jfif",
    "client_job_duration": "5",
    "data_pendapatan_suami": "3000000",
    "data_suami_pendidikan": "Perguruan Tinggi & Sederajat",
    "data_suami_alamat": "jakarta",
    "desa_penanggung_jawab": "Duren Tiga",
    "desa_penanggung_jawab_id": 4730,
    "client_fullname_id_card_penanggung_jawab": "gertu",
    "client_ktp_penanggung_jawab": "6161619180001578",
    "data_suami_marital_status": "Belum Menikah",
    "data_suami_tgllahir": "1982-02-08",
    "data_hubungan": "Kakak/Adik",
    "kota_kab_penanggung_jawab": "Jakarta Selatan",
    "kota_kab_penanggung_jawab_id": 56,
    "data_suami_pekerjaan": "C32909",
    "client_id_card_valid_through_penanggung_jawab_type": "seumur_hidup",
    "client_nationality_penanggung_jawab": "wni",
    "data_suami_tempatlahir": "medan",
    "rt_penanggung_jawab": "002",
    "client_identity_type_penanggung_jawab": "ktp",
    "kode_pos_penanggung_jawab": "12760",
    "provinsi_penanggung_jawab": "DKI Jakarta",
    "provinsi_penanggung_jawab_id": 31,
    "job_address_penanggung_jawab": "jakarta",
    "data_suami_alamat_flag": "sama_dengan_id_card",
    "sumber_dana_penanggung_jawab": "hasil_usaha",
    "rw_penanggung_jawab": "003",
    "kecamatan_penanggung_jawab": "Pancoran",
    "client_phone_penanggung_jawab": "08124684578",
    "data_suami_umur": 40,
    "client_id_card_valid_through_penanggung_jawab": "2072-02-08",
    "data_sector": "3",
    "data_rencana_angsuran": "50000",
    "data_pengajuan": "5000000",
    "data_jangkawaktu": "50",
    "data_ke": "0",
    "data_tujuan": "Makanan Kecil",
    "group": "(77) Giri",
    "groupId": 1000008734,
    "data_popi_jenislantai": "B",
    "data_rmc_jenisdinding": "A",
    "data_popi_kulkas": "B",
    "data_popi_bahanbakar": "B",
    "data_rmc_jenislantai": "A",
    "data_popi_motor": "B",
    "client_no_kk":"1234567890123456",
    "fingerprint_bypassed": false,
    "survey_signature_url": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/674be1b2-2cda-43ca-b6b6-ec0c9b5541e9.jfif"
  },
  "taskStatus": "COMPLETED",
  "uuid": "86e5c71d-533b-4e95-ac25-86ad752be586"
}' && echo "job done 1" &

curl --location --request POST 'localhost:9001/uk/api/v3/submit-survey' \
    --header 'Content-Type: application/json' \
    --header 'access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c24iOiJrYWJhdGJwIiwicm9sIjoiRk8iLCJleHAiOjE2NjMxMDEyNjYsImp0aSI6IjE0NjEiLCJpYXQiOjE2NjMwNDEyNjYsImlzcyI6ImdvLWNhcyIsIm5iZiI6MTY2MzA0MTI2Niwic3ViIjoiQVBQIn0.KIQcS2NezWP7htiiSWmnUPbFtWvOiz4nCQSifjdem-8' \
    --header 'assignee: AGENT' \
    --header 'assigneeId: 1461' \
    --header 'Accept: application/vnd.amartha.superapp+json;version=3' \
    --data-raw '{
    "actualLocation": {
        "latitude": -0.1942736,
        "longitude": 100.5796257
    },
    "agentId": 1461,
    "borrowerConsent": true,
    "branchId": 380,
    "fullname": "Test Double Submit",
    "groupId": 1000008734,
    "isLoadNik": false,
    "isOcr": false,
    "raw": {
        "client_fullname_id_card": "Test Double Submit",
        "client_ktp": "3573210912984103",
        "photo_kk": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/8116c19e-e24c-4874-a12f-2b033c780d02.jfif",
        "client_job_geotagging": {
        "latitude": -0.19424252256835878,
        "longitude": 100.57965226471424,
        "name": "Custom Address"
        },
        "photo_ktp": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/36cda798-ea65-456b-917d-4e4af524c7cd.jfif",
        "photo_penanggung_jawab": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/18f775dd-f030-467e-ba64-8a06b0f0a220.jfif",
        "geotagging": {
        "latitude": -0.19424252256835878,
        "longitude": 100.57965226471424,
        "name": "Custom Address"
        },
        "photo_client": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/f02d1e47-1d05-42ce-8ce2-558cd2a01da4.jfif",
        "photo_client_square": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/e83f39d7-d9ea-4518-a9d2-e1d23186e93f.jfif",
        "photo_client_selfie": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/4234ee38-fd3c-4e66-8389-8fd45fe2be94.jfif",
        "geotagging_penanggung_jawab": {
        "latitude": -0.19424252256835878,
        "longitude": 100.57965226471424,
        "name": "Custom Address"
        },
        "photo_ktp_penanggung_jawab": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/16d2f6d4-2441-4407-8ee9-18b970bf4581.jfif",
        "photo_client_house": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/f299515d-f988-4820-988b-37b0c7fc50ad.jfif",
        "loanType": "NORMAL",
        "client_fullname": "Test Double Submit",
        "client_alias": "Sarimin Satu Satu",
        "client_branch": 380,
        "client_total_income_keluarga_monthly": 12000000,
        "client_expense_per_month": 0,
        "client_job_expense_monthly": 0,
        "client_job_phone_no": "085213469578",
        "client_job_type": "Wirausaha",
        "client_job_name": "Usaha Ibu satu",
        "client_job_negara": "Indonesia",
        "client_jenis_kelamin": "Perempuan",
        "client_other_loan_total": -1,
        "client_other_loan_total_amount": -1,
        "data_pendapatan_istri_monthly": 12000000,
        "data_akad": "MBA",
        "data_tgl": "2022-02-08",
        "job_type_penanggung_jawab": "Wirausaha",
        "other_loan_instance_name": "",
        "other_loan_weekly_installment_monthly": 0,
        "client_job_rt": "002",
        "client_job_rw": "003",
        "client_job_kode_pos": "12760",
        "client_job_provinsi": "DKI Jakarta",
        "client_job_kota_kab": "Jakarta Selatan",
        "client_job_kecamatan": "Pancoran",
        "client_job_desa": "Duren Tiga",
        "data_suami": "gertu",
        "client_alias_penanggung_jawab": "gertu",
        "tanggungan": "[]",
        "uuid": "86e5c71d-533b-4e95-ac25-86ad752be586",
        "client_kota_kab": "Jakarta Selatan",
        "client_kota_kab_id": 56,
        "client_sumber_dana": "hasil_usaha",
        "client_provinsi": "DKI Jakarta",
        "client_provinsi_id": 31,
        "client_total_income_keluarga": "3000000",
        "client_nationality": "wni",
        "client_alamat": "jakarta",
        "client_birthplace": "medan",
        "client_desa": "Duren Tiga",
        "client_desa_id": 4730,
        "client_domicile_equals_id_card": "sama_dengan_id_card",
        "client_phone": "081345410545",
        "client_kecamatan": "Pancoran",
        "client_kecamatan_id": 727,
        "client_identity_type": "ktp",
        "client_id_card_valid_type": "seumur_hidup",
        "data_client_kehamilan": "Tidak Hamil dan Tidak Menyusui",
        "client_religion": "Islam",
        "client_permanent_resident": true,
        "client_kode_pos": "12760",
        "client_alamat_rekening_koran": "id_card_address",
        "client_other_loan": [],
        "client_birthdate": "1952-02-08",
        "client_education": "Perguruan Tinggi & Sederajat",
        "client_rt": "002",
        "client_rw": "003",
        "client_ibu_kandung": "santini",
        "client_expense_per_week": "0",
        "client_maritalstatus": "Belum Menikah",
        "client_job_expense": "0",
        "data_pendapatan_istri": "3000000",
        "client_domicile_alamat": "jakarta",
        "client_domicile_rt": "002",
        "client_domicile_rw": "003",
        "client_domicile_kode_pos": "12760",
        "client_domicile_provinsi": "DKI Jakarta",
        "client_domicile_kota_kab": "Jakarta Selatan",
        "client_domicile_kecamatan": "Pancoran",
        "client_domicile_desa": "Duren Tiga",
        "client_job_address": "jakarta",
        "data_client_umur": 40,
        "is_tnc_approved":false,
        "client_id_card_valid_through": "2072-02-08",
        "kecamatan_penanggung_jawab_id": 727,
        "client_face_identity": {
        "is_enrolled": true
        },
        "client_digital_signature": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/674be1b2-2cda-43ca-b6b6-ec0c9b5541e9.jfif",
        "client_pj_digital_signature":"",
        "client_job": "C32909",
        "data_pendapatan_lain": "3000000",
        "rekening_mitra_nama":        "Yuhu",
        "rekening_mitra_bank_tujuan": "BRI",
        "rekening_mitra_no_rekening": "123456789012345", 
        "photo_buku_tabungan":"https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/4234ee38-fd3c-4e66-8389-8fd45fe2be94.jfif",
        "client_job_duration": "5",
        "data_pendapatan_suami": "3000000",
        "data_suami_pendidikan": "Perguruan Tinggi & Sederajat",
        "data_suami_alamat": "jakarta",
        "desa_penanggung_jawab": "Duren Tiga",
        "desa_penanggung_jawab_id": 4730,
        "client_fullname_id_card_penanggung_jawab": "gertu",
        "client_ktp_penanggung_jawab": "6161619180001578",
        "data_suami_marital_status": "Belum Menikah",
        "data_suami_tgllahir": "1982-02-08",
        "data_hubungan": "Kakak/Adik",
        "kota_kab_penanggung_jawab": "Jakarta Selatan",
        "kota_kab_penanggung_jawab_id": 56,
        "data_suami_pekerjaan": "C32909",
        "client_id_card_valid_through_penanggung_jawab_type": "seumur_hidup",
        "client_nationality_penanggung_jawab": "wni",
        "data_suami_tempatlahir": "medan",
        "rt_penanggung_jawab": "002",
        "client_identity_type_penanggung_jawab": "ktp",
        "kode_pos_penanggung_jawab": "12760",
        "provinsi_penanggung_jawab": "DKI Jakarta",
        "provinsi_penanggung_jawab_id": 31,
        "job_address_penanggung_jawab": "jakarta",
        "data_suami_alamat_flag": "sama_dengan_id_card",
        "sumber_dana_penanggung_jawab": "hasil_usaha",
        "rw_penanggung_jawab": "003",
        "kecamatan_penanggung_jawab": "Pancoran",
        "client_phone_penanggung_jawab": "081313070545",
        "data_suami_umur": 40,
        "client_id_card_valid_through_penanggung_jawab": "2072-02-08",
        "data_sector": "3",
        "data_rencana_angsuran": "50000",
        "data_pengajuan": "5000000",
        "data_jangkawaktu": "50",
        "data_ke": "0",
        "data_tujuan": "Makanan Kecil",
        "group": "(77) Giri",
        "groupId": 1000008734,
        "data_popi_jenislantai": "B",
        "data_rmc_jenisdinding": "A",
        "data_popi_kulkas": "B",
        "data_popi_bahanbakar": "B",
        "data_rmc_jenislantai": "A",
        "data_popi_motor": "B",
        "client_no_kk":"1234567890123456",
        "fingerprint_bypassed": false,
        "survey_signature_url": "https://storage.googleapis.com/ddd-file-storage-dev/survey/1328622/674be1b2-2cda-43ca-b6b6-ec0c9b5541e9.jfif"
    },
    "taskStatus": "COMPLETED",
    "uuid": "86e5c71d-533b-4e95-ac25-86ad752be586"
}' && echo "job done 2" &

wait
